export const indicators = [
	{ name: 'ISO Country code' },
	{ name: 'population' },
	{ name: 'surface area (Km2)' },
	{ name: 'GINI index' },
	{ name: 'happy planet index' },
	{ name: 'human development index' },
	{ name: 'world happiness report score' },
	{ name: 'sustainable economic development assessment (SEDA)' },
	{ name: '"GDP (billions PPP)"' },
	{ name: 'GDP per capita (PPP)' },
	{ name: '"GDP growth (annual %)"' },
	{ name: '"health expenditure % of GDP"' },
	{ name: '"health expenditure per person"' },
	{ name: '"education expenditure % of GDP"' },
	{ name: '"education expenditure per person "' },
	{ name: 'school life expectancy (YEARS)' },
	{ name: 'unemployment (%)' },
	{ name: 'government spending score' },
	{ name: 'government expenditure (% of GDP)' },
	{ name: 'political rights score ' },
	{ name: 'civil liberties score ' },
	{ name: 'political stability & absence of violence' },
	{ name: 'government effectiveness' },
	{ name: 'regulatory quality' },
	{ name: 'rule of law' },
	{ name: 'control of corruption' },
	{ name: 'judicial effectiveness score' },
	{ name: 'government integrity score' },
	{ name: 'property rights score' },
	{ name: 'tax burden score' },
	{ name: 'overall economic freedom score' },
	{ name: 'financial freedom score' },
	{ name: 'women MPs (% of all MPs)' },
];
