export const indicators = [
	{
		id: 'population',
		name: 'Population',
		source: 'World Bank Data',
		URL: 'https://data.worldbank.org/indicator/SP.POP.TOTL',
		notes: '',
		'data year': 2018,
		type: 'info',
		format: 'number',
	},
	{
		id: 'surface area (Km2)',
		name: 'Surface Area (km2)',
		source: 'CIA World Factbook',
		URL:
			'https://www.cia.gov/library/publications/the-world-factbook/fields/2147.html#al',
		notes: '',
		'data year': 2018,
		type: 'info',
		format: 'area',
	},
	{
		id: 'GINI index',
		name: 'GINI Index',
		source: 'CIA World Factbook',
		URL:
			'https://www.cia.gov/library/publications/the-world-factbook/rankorder/2172rank.html',
		notes: 'Inequality in the distribution of family income. Lower the better.',
		'data year': 'varies by country',
		type: 'economy',
		format: 'number',
	},
	{
		id: 'happy planet index',
		name: 'Happy Planet Index',
		source: 'Happy Planet Index',
		URL: 'http://happyplanetindex.org/',
		notes:
			'Well being + life expectancy + inequalities + ecological footprint  \n(higher = better)',
		'data year': 2016,
		type: 'life',
	},
	{
		id: 'human development index',
		name: 'Human Development Index',
		source: 'UNDP',
		URL: 'http://hdr.undp.org/en/data#',
		notes: 'Healthy life + knowledge + standard of living  \n(high = better)',
		'data year': 2017,
		type: 'life',
	},
	{
		id: 'world happiness report score',
		name: 'World Happiness Report Score',
		source: 'World Happiness Report',
		URL: 'http://worldhappiness.report/ed/2018/',
		notes:
			'Polled inhabitants rate their quality of life from 1-10\n(higher = better)',
		'data year': 2017,
		type: 'life',
	},
	{
		id: 'sustainable economic development assessment (SEDA)',
		name: 'Sustainable Economic Development Assessment (SEDA)',
		source: 'Boston Consulting Group (BCG)',
		URL:
			'https://www.bcg.com/en-gb/publications/interactives/seda-2018-guide.aspx',
		notes:
			'An assessment based on 40 indicators in sustainability, economics, & investments\n(higher = better)',
		'data year': 2018,
		type: 'economy',
	},
	{
		id: 'GDP (billions PPP)',
		name: 'GDP (billions PPP)',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes: '',
		'data year': 2018,
		type: 'economy',
		format: 'dollar',
	},
	{
		id: 'GDP per capita (PPP)',
		name: 'GDP per Capita (PPP)',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes: '',
		'data year': 2018,
		type: 'economy',
		format: 'dollar',
	},
	{
		id: 'GDP growth (annual %)',
		name: 'GDP Growth (annual %)',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes: '',
		'data year': 2018,
		type: 'economy',
		format: 'percentage',
	},
	{
		id: 'health expenditure % of GDP',
		name: 'Health Expenditure % of GDP',
		source: 'World Bank',
		URL: 'https://data.worldbank.org/indicator/SH.XPD.CHEX.GD.ZS',
		notes: '',
		'data year': 2015,
		type: 'health',
		format: 'percentage',
	},
	{
		id: 'health expenditure per person',
		name: 'Health Expenditure per Person',
		source: 'World Bank',
		URL: 'https://data.worldbank.org/indicator/SH.XPD.CHEX.PP.CD',
		notes: '(current international $)',
		'data year': 2015,
		type: 'health',
		format: 'dollar',
	},
	{
		id: 'education expenditure % of GDP',
		name: 'Education Expenditure % of GDP',
		source: 'World Bank',
		URL: 'https://data.worldbank.org/indicator/SE.XPD.TOTL.GD.ZS?view=chart',
		notes: '',
		'data year': 2014,
		type: 'education',
		format: 'percentage',
	},
	{
		id: 'education expenditure per person',
		name: 'Education Expenditure per Person',
		source: 'our calcs',
		URL: '',
		notes: '(current USD per capita)',
		'data year': '2,014',
		type: 'education',
		format: 'dollar',
	},
	{
		id: 'school life expectancy (YEARS)',
		name: 'School Life Expectancy (years)',
		source: 'CIA World Factbook',
		URL:
			'https://www.cia.gov/library/publications/the-world-factbook/fields/2205.html#202',
		notes: 'Average male & female, primary to tertiary (years)',
		'data year': 'latest year',
		type: 'education',
		format: 'years',
	},
	{
		id: 'unemployment (%)',
		name: 'Unemployment (%)',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes: '',
		'data year': 2018,
		type: 'economy',
		format: 'percentage',
	},
	{
		id: 'government spending score',
		name: 'Government Spending Score',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes: 'Burden of gov spending on the country (0 = best)',
		'data year': 2018,
		type: 'goverment',
	},
	{
		id: 'government expenditure (% of GDP)',
		name: 'Government Expenditure (% of GDP)',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes: '',
		'data year': 2018,
		type: 'economy',
		format: 'percentage',
	},
	{
		id: 'political rights score',
		name: 'Political Rights Score',
		source: 'Freedom House',
		URL: 'https://freedomhouse.org/content/freedom-world-data-and-resources',
		notes: 'Out of 7\n (lower = better)',
		'data year': 2017,
		type: 'government',
	},
	{
		id: 'civil liberties score',
		name: 'Civil Liberties Score',
		source: 'Freedom House',
		URL: 'https://freedomhouse.org/content/freedom-world-data-and-resources',
		notes: 'Out of 7\n (lower = better)',
		'data year': 2017,
		type: 'government',
	},
	{
		id: 'political stability & absence of violence',
		name: 'Political Stability & Absence of Violence',
		source: 'World Bank',
		URL: 'http://info.worldbank.org/governance/wgi/#home',
		notes: 'Likelihood of political instability',
		'data year': 2017,
		type: 'government',
	},
	{
		id: 'government effectiveness',
		name: 'Government Effectiveness',
		source: 'World Bank',
		URL: 'http://info.worldbank.org/governance/wgi/#home',
		notes:
			'Quality of public services, civil service, policy formation, government commitment (-2.5 to +2.5)',
		'data year': 2017,
		type: 'government',
	},
	{
		id: 'regulatory quality',
		name: 'Regulatory Quality',
		source: 'World Bank',
		URL: 'http://info.worldbank.org/governance/wgi/#home',
		notes: 'Level of policies to support private sector',
		'data year': 2017,
		type: 'government',
	},
	{
		id: 'rule of law',
		name: 'Rule of Law',
		source: 'World Bank',
		URL: 'http://info.worldbank.org/governance/wgi/#home',
		notes: 'Quality of rule of law + likelihood of crime / violence',
		'data year': 2017,
		type: 'justice',
	},
	{
		id: 'control of corruption',
		name: 'Control of Corruption',
		source: 'World Bank',
		URL: 'http://info.worldbank.org/governance/wgi/#home',
		notes: '',
		'data year': 2017,
		type: 'justice',
	},
	{
		id: 'judicial effectiveness score',
		name: 'Judicial Effectiveness Score',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes:
			'Judicial independence + quality of the judicial process,\nfairness\n(/100)',
		'data year': 2018,
		type: 'justice',
	},
	{
		id: 'government integrity score',
		name: 'Government Integrity Score',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes: 'Public trust + transparency + corruption',
		'data year': 2018,
		type: 'government',
	},
	{
		id: 'property rights score',
		name: 'Property Rights Score',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes: 'How freely can inhabitants acquire private property?',
		'data year': 2018,
		type: 'economy',
	},
	{
		id: 'tax burden score',
		name: 'Tax Burden Score',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes: 'Individual tax rate + corporate tax rate + total tax as % of GDP',
		'data year': 2018,
		type: 'economy',
	},
	{
		id: 'overall economic freedom score',
		name: 'Overall Economic Freedom Score',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes: '',
		'data year': 2017,
		type: 'economy',
	},
	{
		id: 'financial freedom score',
		name: 'Financial Freedom Score',
		source: 'Heritage Foundation',
		URL: 'https://www.heritage.org/index/explore',
		notes:
			'Level of gov regulation of financial services, foreign competition, credit & capital development',
		'data year': 2018,
		type: 'government',
	},
	{
		id: 'women MPs (% of all MPs)',
		name: 'Women MPs (% of all MPs)',
		source: 'World Bank',
		URL: 'https://data.worldbank.org/indicator/SG.GEN.PARL.ZS',
		notes: '',
		'data year': 2017,
		type: 'government',
		format: 'percentage',
	},
];

export const indicatorGroups = [
	'info',
	'life',
	'economy',
	'government',
	'health',
	'education',
	'justice',
];

export const continents = [
	{
		name: 'Africa',
		colour: '#D10FC9',
	},
	{
		name: 'Asia',
		colour: '#5F0FD1',
	},
	{
		name: 'Europe',
		colour: '#0FA6D1',
	},
	{
		name: 'North America',
		colour: '#0FD165',
	},
	{
		name: 'Oceania',
		colour: '#FFE813',
	},
	{
		name: 'South America',
		colour: '#FF5C13',
	},
];

export const countries = [
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'AF',
		Country_Code_3: 'AFG',
		Country_Name: 'Afghanistan',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'AL',
		Country_Code_3: 'ALB',
		Country_Name: 'Albania',
	},
	{
		Continent_Code: 'Antarctica',
		Country_Code_2: 'AQ',
		Country_Code_3: 'ATA',
		Country_Name: 'Antarctica (the territory South of 60 deg S)',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'DZ',
		Country_Code_3: 'DZA',
		Country_Name: 'Algeria',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'AS',
		Country_Code_3: 'ASM',
		Country_Name: 'American Samoa',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'AD',
		Country_Code_3: 'AND',
		Country_Name: 'Andorra',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'AO',
		Country_Code_3: 'AGO',
		Country_Name: 'Angola',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'AG',
		Country_Code_3: 'ATG',
		Country_Name: 'Antigua and Barbuda',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'AZ',
		Country_Code_3: 'AZE',
		Country_Name: 'Azerbaijan',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'AZ',
		Country_Code_3: 'AZE',
		Country_Name: 'Azerbaijan',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'AR',
		Country_Code_3: 'ARG',
		Country_Name: 'Argentina',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'AU',
		Country_Code_3: 'AUS',
		Country_Name: 'Australia',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'AT',
		Country_Code_3: 'AUT',
		Country_Name: 'Austria',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'BS',
		Country_Code_3: 'BHS',
		Country_Name: 'Bahamas the',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'BH',
		Country_Code_3: 'BHR',
		Country_Name: 'Bahrain',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'BD',
		Country_Code_3: 'BGD',
		Country_Name: 'Bangladesh',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'AM',
		Country_Code_3: 'ARM',
		Country_Name: 'Armenia',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'AM',
		Country_Code_3: 'ARM',
		Country_Name: 'Armenia',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'BB',
		Country_Code_3: 'BRB',
		Country_Name: 'Barbados',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'BE',
		Country_Code_3: 'BEL',
		Country_Name: 'Belgium',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'BM',
		Country_Code_3: 'BMU',
		Country_Name: 'Bermuda',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'BT',
		Country_Code_3: 'BTN',
		Country_Name: 'Bhutan',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'BO',
		Country_Code_3: 'BOL',
		Country_Name: 'Bolivia',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'BA',
		Country_Code_3: 'BIH',
		Country_Name: 'Bosnia and Herzegovina',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'BW',
		Country_Code_3: 'BWA',
		Country_Name: 'Botswana',
	},
	{
		Continent_Code: 'Antarctica',
		Country_Code_2: 'BV',
		Country_Code_3: 'BVT',
		Country_Name: 'Bouvet Island (Bouvetoya)',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'BR',
		Country_Code_3: 'BRA',
		Country_Name: 'Brazil',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'BZ',
		Country_Code_3: 'BLZ',
		Country_Name: 'Belize',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'IO',
		Country_Code_3: 'IOT',
		Country_Name: 'British Indian Ocean Territory (Chagos Archipelago)',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'SB',
		Country_Code_3: 'SLB',
		Country_Name: 'Solomon Islands',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'VG',
		Country_Code_3: 'VGB',
		Country_Name: 'British Virgin Islands',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'BN',
		Country_Code_3: 'BRN',
		Country_Name: 'Brunei Darussalam',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'BG',
		Country_Code_3: 'BGR',
		Country_Name: 'Bulgaria',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'MM',
		Country_Code_3: 'MMR',
		Country_Name: 'Myanmar',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'BI',
		Country_Code_3: 'BDI',
		Country_Name: 'Burundi',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'BY',
		Country_Code_3: 'BLR',
		Country_Name: 'Belarus',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'KH',
		Country_Code_3: 'KHM',
		Country_Name: 'Cambodia',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'CM',
		Country_Code_3: 'CMR',
		Country_Name: 'Cameroon',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'CA',
		Country_Code_3: 'CAN',
		Country_Name: 'Canada',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'CV',
		Country_Code_3: 'CPV',
		Country_Name: 'Cape Verde',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'KY',
		Country_Code_3: 'CYM',
		Country_Name: 'Cayman Islands',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'CF',
		Country_Code_3: 'CAF',
		Country_Name: 'Central African Republic',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'LK',
		Country_Code_3: 'LKA',
		Country_Name: 'Sri Lanka',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'TD',
		Country_Code_3: 'TCD',
		Country_Name: 'Chad',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'CL',
		Country_Code_3: 'CHL',
		Country_Name: 'Chile',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'CN',
		Country_Code_3: 'CHN',
		Country_Name: 'China',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'TW',
		Country_Code_3: 'TWN',
		Country_Name: 'Taiwan',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'CX',
		Country_Code_3: 'CXR',
		Country_Name: 'Christmas Island',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'CC',
		Country_Code_3: 'CCK',
		Country_Name: 'Cocos (Keeling) Islands',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'CO',
		Country_Code_3: 'COL',
		Country_Name: 'Colombia',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'KM',
		Country_Code_3: 'COM',
		Country_Name: 'Comoros, Union of the',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'YT',
		Country_Code_3: 'MYT',
		Country_Name: 'Mayotte',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'CG',
		Country_Code_3: 'COG',
		Country_Name: 'Congo the',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'CD',
		Country_Code_3: 'COD',
		Country_Name: 'Congo',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'CK',
		Country_Code_3: 'COK',
		Country_Name: 'Cook Islands',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'CR',
		Country_Code_3: 'CRI',
		Country_Name: 'Costa Rica',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'HR',
		Country_Code_3: 'HRV',
		Country_Name: 'Croatia',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'CU',
		Country_Code_3: 'CUB',
		Country_Name: 'Cuba',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'CY',
		Country_Code_3: 'CYP',
		Country_Name: 'Cyprus',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'CY',
		Country_Code_3: 'CYP',
		Country_Name: 'Cyprus',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'CZ',
		Country_Code_3: 'CZE',
		Country_Name: 'Czech Republic',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'BJ',
		Country_Code_3: 'BEN',
		Country_Name: 'Benin',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'DK',
		Country_Code_3: 'DNK',
		Country_Name: 'Denmark',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'DM',
		Country_Code_3: 'DMA',
		Country_Name: 'Dominica',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'DO',
		Country_Code_3: 'DOM',
		Country_Name: 'Dominican Republic',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'EC',
		Country_Code_3: 'ECU',
		Country_Name: 'Ecuador',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'SV',
		Country_Code_3: 'SLV',
		Country_Name: 'El Salvador',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'GQ',
		Country_Code_3: 'GNQ',
		Country_Name: 'Equatorial Guinea',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'ET',
		Country_Code_3: 'ETH',
		Country_Name: 'Ethiopia',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'ER',
		Country_Code_3: 'ERI',
		Country_Name: 'Eritrea',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'EE',
		Country_Code_3: 'EST',
		Country_Name: 'Estonia',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'FO',
		Country_Code_3: 'FRO',
		Country_Name: 'Faroe Islands',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'FK',
		Country_Code_3: 'FLK',
		Country_Name: 'Falkland Islands (Malvinas)',
	},
	{
		Continent_Code: 'Antarctica',
		Country_Code_2: 'GS',
		Country_Code_3: 'SGS',
		Country_Name: 'South Georgia and the South Sandwich Islands',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'FJ',
		Country_Code_3: 'FJI',
		Country_Name: 'Fiji',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'FI',
		Country_Code_3: 'FIN',
		Country_Name: 'Finland',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'AX',
		Country_Code_3: 'ALA',
		Country_Name: 'Åland Islands',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'FR',
		Country_Code_3: 'FRA',
		Country_Name: 'France',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'GF',
		Country_Code_3: 'GUF',
		Country_Name: 'French Guiana',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'PF',
		Country_Code_3: 'PYF',
		Country_Name: 'French Polynesia',
	},
	{
		Continent_Code: 'Antarctica',
		Country_Code_2: 'TF',
		Country_Code_3: 'ATF',
		Country_Name: 'French Southern Territories',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'DJ',
		Country_Code_3: 'DJI',
		Country_Name: 'Djibouti',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'GA',
		Country_Code_3: 'GAB',
		Country_Name: 'Gabon',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'GE',
		Country_Code_3: 'GEO',
		Country_Name: 'Georgia',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'GE',
		Country_Code_3: 'GEO',
		Country_Name: 'Georgia',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'GM',
		Country_Code_3: 'GMB',
		Country_Name: 'Gambia',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'PS',
		Country_Code_3: 'PSE',
		Country_Name: 'Palestinian Territory',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'DE',
		Country_Code_3: 'DEU',
		Country_Name: 'Germany',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'GH',
		Country_Code_3: 'GHA',
		Country_Name: 'Ghana',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'GI',
		Country_Code_3: 'GIB',
		Country_Name: 'Gibraltar',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'KI',
		Country_Code_3: 'KIR',
		Country_Name: 'Kiribati',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'GR',
		Country_Code_3: 'GRC',
		Country_Name: 'Greece',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'GL',
		Country_Code_3: 'GRL',
		Country_Name: 'Greenland',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'GD',
		Country_Code_3: 'GRD',
		Country_Name: 'Grenada',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'GP',
		Country_Code_3: 'GLP',
		Country_Name: 'Guadeloupe',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'GU',
		Country_Code_3: 'GUM',
		Country_Name: 'Guam',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'GT',
		Country_Code_3: 'GTM',
		Country_Name: 'Guatemala',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'GN',
		Country_Code_3: 'GIN',
		Country_Name: 'Guinea',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'GY',
		Country_Code_3: 'GUY',
		Country_Name: 'Guyana',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'HT',
		Country_Code_3: 'HTI',
		Country_Name: 'Haiti',
	},
	{
		Continent_Code: 'Antarctica',
		Country_Code_2: 'HM',
		Country_Code_3: 'HMD',
		Country_Name: 'Heard Island and McDonald Islands',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'VA',
		Country_Code_3: 'VAT',
		Country_Name: 'Holy See (Vatican City State)',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'HN',
		Country_Code_3: 'HND',
		Country_Name: 'Honduras',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'HK',
		Country_Code_3: 'HKG',
		Country_Name: 'Hong Kong',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'HU',
		Country_Code_3: 'HUN',
		Country_Name: 'Hungary',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'IS',
		Country_Code_3: 'ISL',
		Country_Name: 'Iceland',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'IN',
		Country_Code_3: 'IND',
		Country_Name: 'India',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'ID',
		Country_Code_3: 'IDN',
		Country_Name: 'Indonesia',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'IR',
		Country_Code_3: 'IRN',
		Country_Name: 'Iran',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'IQ',
		Country_Code_3: 'IRQ',
		Country_Name: 'Iraq',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'IE',
		Country_Code_3: 'IRL',
		Country_Name: 'Ireland',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'IL',
		Country_Code_3: 'ISR',
		Country_Name: 'Israel',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'IT',
		Country_Code_3: 'ITA',
		Country_Name: 'Italy',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'CI',
		Country_Code_3: 'CIV',
		Country_Name: "Cote d'Ivoire",
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'JM',
		Country_Code_3: 'JAM',
		Country_Name: 'Jamaica',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'JP',
		Country_Code_3: 'JPN',
		Country_Name: 'Japan',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'KZ',
		Country_Code_3: 'KAZ',
		Country_Name: 'Kazakhstan',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'KZ',
		Country_Code_3: 'KAZ',
		Country_Name: 'Kazakhstan',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'JO',
		Country_Code_3: 'JOR',
		Country_Name: 'Jordan',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'KE',
		Country_Code_3: 'KEN',
		Country_Name: 'Kenya',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'KP',
		Country_Code_3: 'PRK',
		Country_Name: 'Korea',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'KR',
		Country_Code_3: 'KOR',
		Country_Name: 'Korea',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'KW',
		Country_Code_3: 'KWT',
		Country_Name: 'Kuwait',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'KG',
		Country_Code_3: 'KGZ',
		Country_Name: 'Kyrgyz Republic',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'LA',
		Country_Code_3: 'LAO',
		Country_Name: "Lao People's Democratic Republic",
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'LB',
		Country_Code_3: 'LBN',
		Country_Name: 'Lebanon',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'LS',
		Country_Code_3: 'LSO',
		Country_Name: 'Lesotho',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'LV',
		Country_Code_3: 'LVA',
		Country_Name: 'Latvia',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'LR',
		Country_Code_3: 'LBR',
		Country_Name: 'Liberia',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'LY',
		Country_Code_3: 'LBY',
		Country_Name: 'Libya',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'LI',
		Country_Code_3: 'LIE',
		Country_Name: 'Liechtenstein',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'LT',
		Country_Code_3: 'LTU',
		Country_Name: 'Lithuania',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'LU',
		Country_Code_3: 'LUX',
		Country_Name: 'Luxembourg',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'MO',
		Country_Code_3: 'MAC',
		Country_Name: 'Macao',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'MG',
		Country_Code_3: 'MDG',
		Country_Name: 'Madagascar',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'MW',
		Country_Code_3: 'MWI',
		Country_Name: 'Malawi',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'MY',
		Country_Code_3: 'MYS',
		Country_Name: 'Malaysia',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'MV',
		Country_Code_3: 'MDV',
		Country_Name: 'Maldives',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'ML',
		Country_Code_3: 'MLI',
		Country_Name: 'Mali',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'MT',
		Country_Code_3: 'MLT',
		Country_Name: 'Malta',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'MQ',
		Country_Code_3: 'MTQ',
		Country_Name: 'Martinique',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'MR',
		Country_Code_3: 'MRT',
		Country_Name: 'Mauritania',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'MU',
		Country_Code_3: 'MUS',
		Country_Name: 'Mauritius',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'MX',
		Country_Code_3: 'MEX',
		Country_Name: 'Mexico',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'MC',
		Country_Code_3: 'MCO',
		Country_Name: 'Monaco',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'MN',
		Country_Code_3: 'MNG',
		Country_Name: 'Mongolia',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'MD',
		Country_Code_3: 'MDA',
		Country_Name: 'Moldova',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'ME',
		Country_Code_3: 'MNE',
		Country_Name: 'Montenegro',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'MS',
		Country_Code_3: 'MSR',
		Country_Name: 'Montserrat',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'MA',
		Country_Code_3: 'MAR',
		Country_Name: 'Morocco',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'MZ',
		Country_Code_3: 'MOZ',
		Country_Name: 'Mozambique',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'OM',
		Country_Code_3: 'OMN',
		Country_Name: 'Oman',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'NA',
		Country_Code_3: 'NAM',
		Country_Name: 'Namibia',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'NR',
		Country_Code_3: 'NRU',
		Country_Name: 'Nauru',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'NP',
		Country_Code_3: 'NPL',
		Country_Name: 'Nepal',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'NL',
		Country_Code_3: 'NLD',
		Country_Name: 'Netherlands',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'AN',
		Country_Code_3: 'ANT',
		Country_Name: 'Netherlands Antilles',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'CW',
		Country_Code_3: 'CUW',
		Country_Name: 'Curaçao',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'AW',
		Country_Code_3: 'ABW',
		Country_Name: 'Aruba',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'SX',
		Country_Code_3: 'SXM',
		Country_Name: 'Sint Maarten (Netherlands)',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'BQ',
		Country_Code_3: 'BES',
		Country_Name: 'Bonaire, Sint Eustatius and Saba',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'NC',
		Country_Code_3: 'NCL',
		Country_Name: 'New Caledonia',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'VU',
		Country_Code_3: 'VUT',
		Country_Name: 'Vanuatu',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'NZ',
		Country_Code_3: 'NZL',
		Country_Name: 'New Zealand',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'NI',
		Country_Code_3: 'NIC',
		Country_Name: 'Nicaragua',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'NE',
		Country_Code_3: 'NER',
		Country_Name: 'Niger',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'NG',
		Country_Code_3: 'NGA',
		Country_Name: 'Nigeria',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'NU',
		Country_Code_3: 'NIU',
		Country_Name: 'Niue',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'NF',
		Country_Code_3: 'NFK',
		Country_Name: 'Norfolk Island',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'NO',
		Country_Code_3: 'NOR',
		Country_Name: 'Norway',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'MP',
		Country_Code_3: 'MNP',
		Country_Name: 'Northern Mariana Islands the',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'UM',
		Country_Code_3: 'UMI',
		Country_Name: 'United States Minor Outlying Islands',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'UM',
		Country_Code_3: 'UMI',
		Country_Name: 'United States Minor Outlying Islands',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'FM',
		Country_Code_3: 'FSM',
		Country_Name: 'Micronesia, Federated States of',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'MH',
		Country_Code_3: 'MHL',
		Country_Name: 'Marshall Islands the',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'PW',
		Country_Code_3: 'PLW',
		Country_Name: 'Palau',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'PK',
		Country_Code_3: 'PAK',
		Country_Name: 'Pakistan',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'PA',
		Country_Code_3: 'PAN',
		Country_Name: 'Panama',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'PG',
		Country_Code_3: 'PNG',
		Country_Name: 'Papua New Guinea',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'PY',
		Country_Code_3: 'PRY',
		Country_Name: 'Paraguay',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'PE',
		Country_Code_3: 'PER',
		Country_Name: 'Peru',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'PH',
		Country_Code_3: 'PHL',
		Country_Name: 'Philippines',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'PN',
		Country_Code_3: 'PCN',
		Country_Name: 'Pitcairn Islands',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'PL',
		Country_Code_3: 'POL',
		Country_Name: 'Poland',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'PT',
		Country_Code_3: 'PRT',
		Country_Name: 'Portugal',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'GW',
		Country_Code_3: 'GNB',
		Country_Name: 'Guinea-Bissau',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'TL',
		Country_Code_3: 'TLS',
		Country_Name: 'Timor-Leste',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'PR',
		Country_Code_3: 'PRI',
		Country_Name: 'Puerto Rico',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'QA',
		Country_Code_3: 'QAT',
		Country_Name: 'Qatar',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'RE',
		Country_Code_3: 'REU',
		Country_Name: 'Reunion',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'RO',
		Country_Code_3: 'ROU',
		Country_Name: 'Romania',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'RU',
		Country_Code_3: 'RUS',
		Country_Name: 'Russian Federation',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'RU',
		Country_Code_3: 'RUS',
		Country_Name: 'Russian Federation',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'RW',
		Country_Code_3: 'RWA',
		Country_Name: 'Rwanda',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'BL',
		Country_Code_3: 'BLM',
		Country_Name: 'Saint Barthelemy',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'SH',
		Country_Code_3: 'SHN',
		Country_Name: 'Saint Helena',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'KN',
		Country_Code_3: 'KNA',
		Country_Name: 'Saint Kitts and Nevis',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'AI',
		Country_Code_3: 'AIA',
		Country_Name: 'Anguilla',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'LC',
		Country_Code_3: 'LCA',
		Country_Name: 'Saint Lucia',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'MF',
		Country_Code_3: 'MAF',
		Country_Name: 'Saint Martin',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'PM',
		Country_Code_3: 'SPM',
		Country_Name: 'Saint Pierre and Miquelon',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'VC',
		Country_Code_3: 'VCT',
		Country_Name: 'Saint Vincent and the Grenadines',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'SM',
		Country_Code_3: 'SMR',
		Country_Name: 'San Marino',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'ST',
		Country_Code_3: 'STP',
		Country_Name: 'Sao Tome and Principe',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'SA',
		Country_Code_3: 'SAU',
		Country_Name: 'Saudi Arabia',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'SN',
		Country_Code_3: 'SEN',
		Country_Name: 'Senegal',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'RS',
		Country_Code_3: 'SRB',
		Country_Name: 'Serbia',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'SC',
		Country_Code_3: 'SYC',
		Country_Name: 'Seychelles',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'SL',
		Country_Code_3: 'SLE',
		Country_Name: 'Sierra Leone',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'SG',
		Country_Code_3: 'SGP',
		Country_Name: 'Singapore',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'SK',
		Country_Code_3: 'SVK',
		Country_Name: 'Slovakia (Slovak Republic)',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'VN',
		Country_Code_3: 'VNM',
		Country_Name: 'Vietnam, Socialist Republic of',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'SI',
		Country_Code_3: 'SVN',
		Country_Name: 'Slovenia',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'SO',
		Country_Code_3: 'SOM',
		Country_Name: 'Somalia, Somali Republic',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'ZA',
		Country_Code_3: 'ZAF',
		Country_Name: 'South Africa',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'ZW',
		Country_Code_3: 'ZWE',
		Country_Name: 'Zimbabwe',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'ES',
		Country_Code_3: 'ESP',
		Country_Name: 'Spain',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'SS',
		Country_Code_3: 'SSD',
		Country_Name: 'South Sudan',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'EH',
		Country_Code_3: 'ESH',
		Country_Name: 'Western Sahara',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'SD',
		Country_Code_3: 'SDN',
		Country_Name: 'Sudan',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'SR',
		Country_Code_3: 'SUR',
		Country_Name: 'Suriname',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'SJ',
		Country_Code_3: 'SJM',
		Country_Name: 'Svalbard & Jan Mayen Islands',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'SZ',
		Country_Code_3: 'SWZ',
		Country_Name: 'Swaziland',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'SE',
		Country_Code_3: 'SWE',
		Country_Name: 'Sweden',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'CH',
		Country_Code_3: 'CHE',
		Country_Name: 'Switzerland, Swiss Confederation',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'SY',
		Country_Code_3: 'SYR',
		Country_Name: 'Syria',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'TJ',
		Country_Code_3: 'TJK',
		Country_Name: 'Tajikistan',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'TH',
		Country_Code_3: 'THA',
		Country_Name: 'Thailand',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'TG',
		Country_Code_3: 'TGO',
		Country_Name: 'Togo, Togolese Republic',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'TK',
		Country_Code_3: 'TKL',
		Country_Name: 'Tokelau',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'TO',
		Country_Code_3: 'TON',
		Country_Name: 'Tonga',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'TT',
		Country_Code_3: 'TTO',
		Country_Name: 'Trinidad and Tobago',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'AE',
		Country_Code_3: 'ARE',
		Country_Name: 'United Arab Emirates',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'TN',
		Country_Code_3: 'TUN',
		Country_Name: 'Tunisia, Tunisian Republic',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'TR',
		Country_Code_3: 'TUR',
		Country_Name: 'Turkey',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'TR',
		Country_Code_3: 'TUR',
		Country_Name: 'Turkey',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'TM',
		Country_Code_3: 'TKM',
		Country_Name: 'Turkmenistan',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'TC',
		Country_Code_3: 'TCA',
		Country_Name: 'Turks and Caicos Islands',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'TV',
		Country_Code_3: 'TUV',
		Country_Name: 'Tuvalu',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'UG',
		Country_Code_3: 'UGA',
		Country_Name: 'Uganda',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'UA',
		Country_Code_3: 'UKR',
		Country_Name: 'Ukraine',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'MK',
		Country_Code_3: 'MKD',
		Country_Name: 'Macedonia',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'EG',
		Country_Code_3: 'EGY',
		Country_Name: 'Egypt',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'GB',
		Country_Code_3: 'GBR',
		Country_Name: 'United Kingdom of Great Britain & Northern Ireland',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'GG',
		Country_Code_3: 'GGY',
		Country_Name: 'Guernsey',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'JE',
		Country_Code_3: 'JEY',
		Country_Name: 'Jersey',
	},
	{
		Continent_Code: 'Europe',
		Country_Code_2: 'IM',
		Country_Code_3: 'IMN',
		Country_Name: 'Isle of Man',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'TZ',
		Country_Code_3: 'TZA',
		Country_Name: 'Tanzania',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'US',
		Country_Code_3: 'USA',
		Country_Name: 'United States of America',
	},
	{
		Continent_Code: 'North America',
		Country_Code_2: 'VI',
		Country_Code_3: 'VIR',
		Country_Name: 'United States Virgin Islands',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'BF',
		Country_Code_3: 'BFA',
		Country_Name: 'Burkina Faso',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'UY',
		Country_Code_3: 'URY',
		Country_Name: 'Uruguay',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'UZ',
		Country_Code_3: 'UZB',
		Country_Name: 'Uzbekistan',
	},
	{
		Continent_Code: 'South America',
		Country_Code_2: 'VE',
		Country_Code_3: 'VEN',
		Country_Name: 'Venezuela',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'WF',
		Country_Code_3: 'WLF',
		Country_Name: 'Wallis and Futuna',
	},
	{
		Continent_Code: 'Oceania',
		Country_Code_2: 'WS',
		Country_Code_3: 'WSM',
		Country_Name: 'Samoa',
	},
	{
		Continent_Code: 'Asia',
		Country_Code_2: 'YE',
		Country_Code_3: 'YEM',
		Country_Name: 'Yemen',
	},
	{
		Continent_Code: 'Africa',
		Country_Code_2: 'ZM',
		Country_Code_3: 'ZMB',
		Country_Name: 'Zambia',
	},
];
